/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Capa_Negocio.clsPaciente;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MendozaGastulo_Tadeo
 */
public class jdListaPacientes extends javax.swing.JDialog {

    clsPaciente objPaciente = new clsPaciente();
    private String dniSeleccionado = "";
    private String nombreSeleccionado = "";

    public jdListaPacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarPacientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        int filaSeleccionada = tblPacientes.getSelectedRow();
        if (filaSeleccionada != -1) {
            dniSeleccionado = tblPacientes.getValueAt(filaSeleccionada, 4).toString();
            nombreSeleccionado=tblPacientes.getValueAt(filaSeleccionada, 1).toString()+tblPacientes.getValueAt(filaSeleccionada, 2).toString()+tblPacientes.getValueAt(filaSeleccionada, 3).toString();
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Deseas escoger el paciente" + nombreSeleccionado + " con dni: " + dniSeleccionado + "?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                dispose();
            }
        }
    }//GEN-LAST:event_tblPacientesMouseClicked
    private void listarPacientes() {
        ResultSet rsPaciente = null;
        String estado = "";
        DefaultTableModel modeloC = new DefaultTableModel();
        modeloC.addColumn("Código");
        modeloC.addColumn("Nombres");
        modeloC.addColumn("Apellido Paterno");
        modeloC.addColumn("Apellido Materno");
        modeloC.addColumn("DNI");
        modeloC.addColumn("Peso");
        modeloC.addColumn("Altura");
        modeloC.addColumn("Fecha de nacimiento");
        modeloC.addColumn("Teléfono");
        modeloC.addColumn("Tipo de sangre");
        modeloC.addColumn("Vigencia");
        tblPacientes.setModel(modeloC);
        try {
            rsPaciente = objPaciente.listarPacientes();
            while (rsPaciente.next()) {
                if (rsPaciente.getString("estado").equals("t")) {
                    estado = "Vigente";
                } else {
                    estado = "No Vigente";
                }
                modeloC.addRow(new Object[]{rsPaciente.getInt("idPaciente"),
                    rsPaciente.getString("nombres"), rsPaciente.getString("apellidoPaterno"),
                    rsPaciente.getString("apellidoMaterno"), rsPaciente.getString("dni"), rsPaciente.getDouble("peso"),
                    rsPaciente.getDouble("altura"), rsPaciente.getString("fecha_nacimiento"), rsPaciente.getString("telefono"),
                    rsPaciente.getString("tipoSangre"), estado});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al listar pacientes -->" + e.getMessage());
        }
    }

    public String getDniDelPaciente() {
        return dniSeleccionado;
    }
    public String getNombreDelPaciente() {
        return nombreSeleccionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables
}
